name: sfa2photo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  http: ^1.5.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/.env